### ISSUE TITLE
Checksum invalid

### ISSUE THREAD

**Issue by iangohye** [yahoo/flux-examples#69] opened 2014-12-13 00:51 UTC
Hi there i tried starting up routing and the chat examples but find that it throws back a warning:
> React attempted to use reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server.

This is not happening on the todo app. I am pretty new to React server side, should i be ignoring this warning?

**Comment by timReynolds** [comment] 2015-01-13 11:23
@mdressman did you find a difference you the diff? 

Would be interested to know if you found the solution. I've not had issues with the demo projects but have with my own. 

Mine seemed to be caused by the fetching of client.js however. If I remove the script tag for client.js the warning goes away. Think I might be including something in the client.js file I shouldn't be.

**Comment by mdressman** [comment] 2015-01-18 02:38
Yes, I was able to pinpoint a place in our code where we were dynamically generating a value rendered independently on server and client.  It turns out they would randomly match 25% of the time which is why the error seemed so sporadic (and frustrating!).  We resolved by stashing this value in a Flux store as we're meant to :)

Removing client.js is getting rid of the invalid checksum warning message because you're removing the client-side React.render() function which generates the error (and all the React magic).

**Comment by timReynolds** [comment] 2015-01-18 14:44
@mdressman Yea, I know what removing the client.js ref had done. Turned out one of the stores wasn't being dehydrated correctly due to a missing return. Which means the store isn't included in the client context hence the incorrect checksum. 

Took ages to work out the cause however but all part of the learning.

**Comment by mridgway** [comment] 2015-01-20 18:36
Tooling can definitely help here. I would love to have a chrome plugin similar to React tools that would allow you to see all of the stores that have been dehydrated. For now, you can expose your `context` object on the `window` and look through its state via the console.

**Closed** 2015-02-03 13:10 UTC

**Comment by Maximilianos** [comment] 2015-02-04 14:59
Hey I am sporadically getting this error for the react-router example with no modifications.

Running on Windows 7 through localhost:3000 on Chrome 40.0.2214.94
All I did was:

```cli
git clone https://github.com/yahoo/flux-examples.git .
npm install
cd react-router
npm run dev ("start" also suffers the same sporadic error)
```

I logged the innerHTML as suggested:
```javascript
app.rehydrate(dehydratedState, function (err, context) {
    ...

    bootstrapDebug('React Rendering');

    console.log(document.getElementById('app').innerHTML);

    Router.run(app.getAppComponent(), HistoryLocation, function (Handler, state) {
        ...
    });

    console.log(document.getElementById('app').innerHTML);

});
```

and though the two logged strings were identical, I still got the error:

```
 Fluxible Fluxible instance instantiated +0ms Object {appComponent: ReactElement}
browser.js:119 Fluxible ApplicationStore store registered +5ms
browser.js:119 Fluxible TimeStore store registered +1ms
browser.js:119 Fluxible PageStore store registered +0ms
browser.js:119 Example rehydrating app +1ms
browser.js:119 Fluxible rehydrate +10ms Object {context: Object, plugins: Object}
browser.js:119 Example React Rendering +1ms
1----> client.js:29 <div data-reactid=".1cnm1z2yry8" data-react-checksum="-1819102077"><ul class="pure-menu pure-menu-open pure-menu-horizontal" data-reactid=".1cnm1z2yry8.0"><li class="pure-menu-selected" data-reactid=".1cnm1z2yry8.0.0"><a href="/" class="active" data-reactid=".1cnm1z2yry8.0.0.0">Home</a></li><li class="" data-reactid=".1cnm1z2yry8.0.1"><a href="/about" class="" data-reactid=".1cnm1z2yry8.0.1.0">About</a></li></ul><p data-reactid=".1cnm1z2yry8.1">Welcome to the site!</p><em style="font-size:.8em;" data-reactid=".1cnm1z2yry8.2">Wed Feb 04 2015 16:53:57 GMT+0200 (GTB Standard Time)</em></div>
2----> client.js:41 <div data-reactid=".1cnm1z2yry8" data-react-checksum="-1819102077"><ul class="pure-menu pure-menu-open pure-menu-horizontal" data-reactid=".1cnm1z2yry8.0"><li class="pure-menu-selected" data-reactid=".1cnm1z2yry8.0.0"><a href="/" class="active" data-reactid=".1cnm1z2yry8.0.0.0">Home</a></li><li class="" data-reactid=".1cnm1z2yry8.0.1"><a href="/about" class="" data-reactid=".1cnm1z2yry8.0.1.0">About</a></li></ul><p data-reactid=".1cnm1z2yry8.1">Welcome to the site!</p><em style="font-size:.8em;" data-reactid=".1cnm1z2yry8.2">Wed Feb 04 2015 16:53:57 GMT+0200 (GTB Standard Time)</em></div>
browser.js:119 Fluxible:Context Executing action  with payload +90ms Object {path: "/", action: null, pathname: "/", routes: Array[2], params: Object…}
browser.js:119 Dispatchr:dispatcher dispatching CHANGE_ROUTE +0ms Object {path: "/", action: null, pathname: "/", routes: Array[2], params: Object…}
browser.js:119 Dispatchr:Action executing handler for TimeStore +1ms
browser.js:119 Dispatchr:dispatcher finished CHANGE_ROUTE +1ms
3----> ReactComponentBrowserEnvironment.js:91 React attempted to use reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server.
browser.js:119 Example React Rendered +8ms
```

**Comment by Maximilianos** [comment] 2015-02-04 15:35
I noticed I was not being as clever as I should be... as I've now noticed the `Example React Rendered` call was happening well after the second supposedly 'rendered' string was being logged...

Anyway putting the `console.log` in the correct place remedied this:
```javascript
    console.log(document.getElementById('app').innerHTML);

    Router.run(app.getAppComponent(), HistoryLocation, function (Handler, state) {
        context.executeAction(navigateAction, state, function () {
            React.withContext(context.getComponentContext(), function () {
                React.render(React.createFactory(Handler)(), mountNode, function () {
                    bootstrapDebug('React Rendered');
                });

                console.log(document.getElementById('app').innerHTML);
            });
        });
    });
```

Diffing the output now I noticed two differences in the logged strings, first is that that 
`data-react-checksum="-2082033167"` was missing in the client-rendered string (is this to be expected when server-client disagree?) and probably more importantly the timestamps were different: 
```
// server                                                                        ↓
<em style="font-size:.8em;" data-reactid=".172htz1i3nk.2">Wed Feb 04 2015 17:18:53 GMT+0200 (GTB Standard Time)</em>
// client                                                                        ↓
<em style="font-size:.8em;" data-reactid=".172htz1i3nk.2">Wed Feb 04 2015 17:18:54 GMT+0200 (GTB Standard Time)</em>
```

**Comment by Schtauffen** [comment] 2015-03-06 05:24
I've run into this error (with both the Yahoo! react-router tutorial, and my own coffee project using that as a spring-board). The difference was with the timestamp:

// server:
Thu Mar 05 2015 23:01:55 GMT-0600 (**CST**)
// client
Thu Mar 05 2015 23:01:55 GMT-0600 (**Central Standard Time**)

My solution is to specify an exact format for the Timestamp component (currently using the moment.js library);
    getState: ->
        time: moment(this.time).format()
    dehydrate: ->
        time: moment(this.time).format()

**Comment by 3den** [comment] 2015-12-01 06:38
@mridgway what should we do in the case when we need to display some component just in the case when the browser supports the feature it provides? 

In my case I am using modernizr to display the file upload button only when the browser has the FileReader api, which means that the server will not display the button but when the client re-renders it will. In that case what is the correct way to remove that warning?

**Comment by redonkulus** [comment] 2015-12-01 22:24
@3den could you leverage componentDidMount to check if FileReader api exists, if so, then re-render to show the button?

**Comment by mridgway** [comment] 2015-12-01 22:26
Right, anything that is browser specific and not detected on the server would have to be done using `componentDidMount` to re-render.
