### ISSUE TITLE
"npm run build" & "npm run dev" not working on Windows

### ISSUE THREAD

**Issue by protron** [yahoo/flux-examples#81] opened 2015-01-14 21:21 UTC
The package.json "scripts" (on each subfolder) have paths like "`../node_modules/.bin/`" before the commands (nodemon, webpack, and grunt).
I suppose they have that in order to use their local versions of those commands instead of requiring them to be globally installed.
The problem is that **Windows** expects paths with "`\`" instead of "`/`", and it's throwing these errors when running the scripts:

    '..' is not recognized as an internal or external command,
    operable program or batch file.

**Comment by mridgway** [comment] 2015-01-14 21:25
Shoot. The problem is that npm sets the `PATH` to the current folder's `node_modules/.bin/` so we need some way to use the parent folders bin path. Not sure how to handle this one other than make each subfolder truly independent with a full package.json.

**Comment by protron** [comment] 2015-01-14 21:27
In case anyone wants a quick fix, I worked around that in 2 ways, but both have their mayor downside:
- [hardcoding the "\" instead of "/"](https://github.com/protron/flux-examples/compare/fix-windows-hardcode): but I suppose it won't work on Linux
- [removing the paths](https://github.com/protron/flux-examples/compare/fix-windows): but we will need to instruct the user to globally install the 3 tools (nodemon, webpack, and grunt) if they don't have them already.

**Comment by redonkulus** [comment] 2015-02-03 18:57
This is fixed in https://github.com/yahoo/flux-examples/pull/97. You do not need the full path to the executable, since its installed in ./node_modules/.bin, npm will find it automatically.

**Closed by redonkulus** 2015-02-03 18:57 UTC
